# This is a basic workflow to help you get started with Actions
# based on https://github.com/Chrede88/cjsolsen.com/blob/master/.github/workflows/main.yml
# https://github.com/wowchemy/wowchemy-hugo-themes/blob/main/.github/workflows/build-test-site.yaml
# https://www.jameswright.xyz/post/20200409/deploy_wowchemy_to_githubio/

name: Build site and deploy to GitHub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch any Git submodules (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install JS dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Check for linting errors
        run: yarn run lint

  hugo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch any Git submodules (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.95.0'
          extended: true

      - name: Build
        run: hugo --minify
